import fs from "fs";
import path from "path";

const pkg = JSON.parse(fs.readFileSync("package.json", "utf8"));

const version = String(pkg.version || "0.0.0");

const outFile = path.resolve("src/ts/infrastructure/version.ts");

const content = `// AUTO-GENERATED FILE
// Generated by scripts/generate-version.mjs
// Do not edit manually.

export const APP_VERSION = "${version}";
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, content);

console.log("Generated version.ts with version:", version);
